- name: Install Nginx
  ansible.builtin.yum:
    name: httpd
    state: installed
- name: remove old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: remove old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


