- name: configuring Erlang repos
  ansible.builtin.shell: curl -s {{ item }} | bash
  loop:
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: install rabbitmq and Erlang
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: restart the rabbit and earlang
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: add application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{roboshop_rabbitmq_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

