- name: diseable mysql
  ansible.builtin.shell: dnf module disable mysql -y

- name: my sql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: restart mysql
  ansible.builtin.systemd:
    name: mysql
    state: restarted
    enabled: yes



