- name: diseable mysql
  ansible.builtin.shell: dnf module disable mysql -y

- name: my sql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: restart mysql
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: reset mysql default password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ${{root_mysql_password}}
  ignore_errors: yes


