- name: copy mongodb yum repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb file
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.khajavali1995.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes

