- name: load MYSQL Schema
  comunity.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}-sql
    login_host: mysql-dev.khajavali1995.online
    login_user: root
    login_password: "{{root_mysql_password }}"